#!/bin/bash

while read local_ref local_sha remote_ref remote_sha
do
  echo $local_ref >> /home/jmc/tmptest
  echo $local_sha >> /home/jmc/tmptest
  echo $remote_ref >> /home/jmc/tmptest
  echo $remote_sha >> /home/jmc/tmptest
  echo "=================================" >> /home/jmc/tmptest
  # Why is this not working?
  if [[ $remote_ref == *"push-hook"* ]]; then
    echo "You should not push to master. Please create a branch."
    exit 1
  fi
done

exit 0

