#!/bin/bash

while read local_ref local_sha remote_ref remote_sha
do
  echo $local_ref
  echo $local_sha
  echo $remote_ref
  echo $remote_sha
  echo "================================="
  echo "================================="
  echo "================================="
  # Why is this not working?
  if [[ $remote_ref == *"push-hook"* ]]; then
    echo "You should not push to master. Please create a branch."
    exit 1
  fi
done

exit 0

